baseURL: "https://jazzy-fox-74bfb6.netlify.app/"
languageCode: en-us
title: Huoyanf's BLOG
theme: PaperMod

params:
  homeInfoParams:
    Title: 'Welcome Stranger'
    Content: 'Welcome to my blog. I am an architecture and self-taught programmer.'

  socialIcons:
    - name: twitter
      url: "https://twitter.com/@hyfthe1"
    - name: github
      url: "https://github.com/duking119"
    - name: linkedin
      url: "https://www.linkedin.com/in/%E5%B2%A9%E9%94%8B-%E9%9C%8D-a70b25b5/"
  cover:
    linkFullImages: true

  ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowShareButtons: true

  ShowPostNavlinks: true
menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30